accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.password, name='password'), 
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/like/', views.like, name='like'),
    path('<int:article_pk>/comment_create/', views.comment_create, name='comment_create'),
    path('<int:comment_pk>/comment_delete/', views.comment_delete, name='comment_delete'),
    path('<int:article_pk>/follow/<int:user_pk>/', views.follow, name='follow'),
]

review/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
]

articles/models.py
from django.db import models
from django.core.validators import EmailValidator, MinValueValidator
from django.conf import settings


# article.liked_users.all()
# user.liked_articles.all()
class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # models.py 에서만 이렇게 가져옴 
    # article.user
    # user.article_set.all()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # related_name 역참조 
    liked_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='liked_articles')

    # 역순 정렬 / migrate 안해도됨 
    class Meta:
        ordering = ('-pk', )


# 1:N 관계가 두개다 
class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        ordering = ('-pk', )


class Person(models.Model):
    name = models.CharField(max_length=10)
    email = models.CharField(
        max_length=100, 
        validators=[EmailValidator(message='이메일 형식에 맞지 않습니다.')]
    )
    age = models.IntegerField(
        validators=[MinValueValidator(19, message='미성년자는 노노')]
    )

articles/forms.py
from django import forms
from .models import Article, Comment


class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = ['title', 'content', ]
        # fields = ['title', ]


class CommentForm(forms.ModelForm):
    # aritcle = forms.ModelChoiceField(
    #     queryset=Article.objects.all(),
    # )

    content = forms.CharField(
        label='댓글',
    )

    class Meta:
        model = Comment
        fields = ['content',]

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST, require_GET
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.http import HttpResponse, JsonResponse
from .models import Article, Comment
from .forms import ArticleForm, CommentForm
from IPython import embed


@require_GET
def index(request):
    articles = Article.objects.all()
    context = {'articles': articles}
    return render(request, 'articles/index.html', context)


# accounts login 이라 login page 로 감 
# @login_required(login_url='/users/login/')
@login_required
def create(request):
    if request.method == 'POST':
        # Article 을 생성해달라고 하는 요청
        form = ArticleForm(request.POST) # title, content
        # embed()
        if form.is_valid(): # 필드에 적힌 내용만 확인, form 에 없는 NOT NULL 값들은 확인 못함 
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect('articles:detail', article.pk)
        # 잘못 입력 되었을 경우 알려줌 
        # else:
        #     context = {'form': form}
        #     return render(request, 'articles/create.html', context)
    else: # GET
        # Article 을 생성하기 위한 페이지를 달라고 하는 요청 
        form = ArticleForm()
    context = {'form': form}
    return render(request, 'articles/create.html', context)


@require_GET
def detail(request, article_pk):
    # 사용자가 url 에 적어보낸 article_pk 를 통해 디테일 페이지를 보여준다.
    article = get_object_or_404(Article, pk=article_pk)
    comments = article.comments.all()
    form = CommentForm()
    context = {
        'article': article,
        'comments': comments,
        'form': form,
    }
    return render(request, 'articles/detail.html', context)
    # 가능
    # return render(request, 'articles/detail.html', {'article': article})


@login_required
def update(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if article.user == request.user:
        # if request.method == 'POST' and article.user == request.user:
        if request.method == 'POST':
            form = ArticleForm(request.POST, instance=article)
            if form.is_valid():
                form.save()
                return redirect('articles:detail', article_pk)
        else:
            # 우와
            form = ArticleForm(instance=article)
    else: 
        return redirect('articles:detail', article_pk)
    context = {'form':form}
    return render(request, 'articles/update.html', context)


# 받는 method 를 POST 로 제한 
@require_POST
# POST 로만 오는데 필요한가...
# GET 요청에서만 사용하면됨 
# @login_required
# GET 요청으로 처리하지 말아야 하는 경우에는 사용하면 안됨 login_required
def delete(request, article_pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=article_pk)
        # if request.method == 'POST':
        if article.user == request.user:
            article.delete()
        else:
            return redirect('articles:detail', article_pk)
        # 보여줄만한 페이지가 따로 없다...
    return redirect('articles:index')


@require_POST
# @login_required
def comment_create(request, article_pk):
    if request.user.is_authenticated:
        # article = get_object_or_404(Article, pk=article_pk)
        form = CommentForm(request.POST)
        if form.is_valid():
            # 임시저장 
            comment = form.save(commit=False)
            comment.article_id = article_pk
            comment.user = request.user
            comment.save()
            return redirect('articles:detail', article_pk)

    # comment = Comment(article_id = article_pk)
    # form = CommentForm(request.POST, instance=comment)
    # form.save()


@require_POST
# @login_required
def comment_delete(request, comment_pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk=comment_pk)
        article_pk = comment.article_id
        article = get_object_or_404(Article, pk=article_pk)
        if comment.user == request.user or article.user == request.user:   
            comment.delete()
        return redirect('articles:detail', article_pk)
    # 쿠키를 지우고 접근할때 
    return HttpResponse('You are Unauthorized', status=401)


@login_required
def like(request, article_pk):
    user = request.user
    article = get_object_or_404(Article, pk=article_pk)
    # exists 한개의 데이터라도 존재하면 true
    if article.liked_users.filter(pk=user.pk).exists():
    # if user in article.liked_users.all():
        user.liked_articles.remove(article)
        liked = False 
    else:
        user.liked_articles.add(article)
        liked = True

    context = {
        'liked': liked, 
        'count': article.liked_users.count()
    }
    return JsonResponse(context)


@login_required
def follow(request, article_pk, user_pk):
    # 로그인한 유저가 게시글 유저를 Follow or unfollow 한다. 
    user = request.user
    person = get_object_or_404(get_user_model(), pk=user_pk)

    if user in person.followers.all(): # 이미 팔로워다
        person.followers.remove(user) # 언팔 
    else:
        person.followers.add(user) # 팔로우함

    return redirect('articles:detail', article_pk)

articles/templates/articles/_follow.html
<div class="jumbotron text-center text-white bg-dark">
  <p class="lead mb-1">작성자 정보</p>
  <h1 class="display-4">{{ article.user.username }}</h1>
  <hr>
  <p class="lead">
    팔로잉 : {{ article.user.followings.all | length }} / 팔로워 : {{ article.user.followers.all | length }}
  </p>
  {% if user != article.user %}
    {% if user in article.user.followers.all %}
    <a href="{% url 'articles:follow' article.pk article.user.pk %}" class="btn btn-primary btn-lg">Unfollow</a>
    {% else %}
    <a href="{% url 'articles:follow' article.pk article.user.pk %}" class="btn btn-primary btn-lg">Follow</a>
    {% endif %} 
  {% endif %}
</div>

articles/templates/articles/create.html
{% extends 'base.html' %}

{% block title %}Article::Create{% endblock title %}

{% block container %}
{% comment %} <form method="POST" action="{% url 'articles:create' %}"> {% endcomment %}
{% comment %} 같은 url 로 간다면 action 이 없어도된다. {% endcomment %}
<form method="POST">
  {% comment %} Cross-site request forgery {% endcomment %}
  {% csrf_token %}
  {{form.as_p}}
  <button class="btn-warning" type="submit">Create</button>
</form>
{% endblock container %}

articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block title %}Article::Detail{% endblock title %}

{% block container %}

<h2>{{ article.title }}</h2>
<p>{{ article.created_at }}</p>
<p>작성자: {{ article.user }}</p>
{% comment %} <a href="{% url 'articles:like' article.pk %}">
  {% if user in article.liked_users.all %}
  <i class="fas fa-heart fa-lg" style="color: red"></i>
  {% else %}
  <i class="far fa-heart fa-lg" style="color: red"></i>
  {% endif %}
</a> {% endcomment %}

<p>
  <i 
    class="{% if user in article.liked_users.all %}fas{% else %}far{% endif %} fa-heart fa-lg" 
    id="like-btn" 
    {% comment %} dataset.id 로 들어감 {% endcomment %}
    data-id="{{ article.pk }}" 
    style="color: red"
  >
  </i>
  <span id="like-count">{{ article.liked_users.all | length }}</span>명이 이 글을 좋아합니다.
</p>
<hr>
<p>{{ article.content }}</p>
<hr>

{% comment %} {% if user.is_authenticated %} {% endcomment %}
{% if article.user == request.user %}
<a href="{% url 'articles:update' article.pk %}">[Update]</a>
<form action="{% url 'articles:delete' article.pk %}" method="POST">
  {% csrf_token %}
  <button class="btn-warning" type="submit">Delete</button>
</form>
<hr>
{% endif %}

{% for comment in comments %}
<span>{{ comment.pk }}. {{ comment.content }} by {{ comment.user }}</span>
{% if comment.user == request.user or article.user == request.user %}
<form action="{% url 'articles:comment_delete' comment.pk %}", method="POST">
  {% csrf_token %}
  <button class="btn btn-link" type="submit">Comment Delete</button>
</form>
<hr>
{% endif %}
{% endfor %}

{% if user.is_authenticated %}
<form action="{% url 'articles:comment_create' article.pk %}", method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button class="btn-warning" type="submit">Comment Create</button>
</form>
{% endif %}

<hr>
{% comment %} 컴포넌트 {% endcomment %}
{% include 'articles/_follow.html' %}

<script>
  const likeBtn = document.querySelector('#like-btn')
  likeBtn.addEventListener('click', function(event) {
    // Button 의 data-id 속성을 아래 코드로 가지고 온다.
    const articleId = event.target.dataset.id
    axios.get(`/articles/${articleId}/like/`)
      .then(function(response) {

        // 사용자의 좋아요 상태에 따라 버튼 클래스 변경 
        if(response.data.liked) {
          likeBtn.classList.remove('far')
          likeBtn.classList.add('fas')
        } else {
          likeBtn.classList.remove('fas')
          likeBtn.classList.add('far')          
        }

        // 아티클을 좋아하는 사람들 수를 응답받아 적용 
        const likeCount = document.querySelector('#like-count')
        likeCount.innerText = response.data.count
      })
  })
</script>
{% endblock container %}

articles/templates/articles/index.html
{% extends 'base.html' %}

{% block title %}Article::Index{% endblock title %}

{% block container %}
<h2>Article List</h2>
{% if user.is_authenticated %}
<a href="{% url 'articles:create' %}">[Create]</a>
{% else %}
<p>로그인해주세요</p>
<a href="{% url 'accounts:signup' %}">가입?</a>
{% endif %}
<hr>
{% for article in articles  %}
<div>
  <h3>{{ article.pk }}. {{ article.title }}</h3> 
  <p>작성자: {{ article.user }}</p>
  <a href="{% url 'articles:detail' article.pk %}">[Detail]</a>
</div>
<br>
{% endfor %}
{% endblock container %}

articles/templates/articles/update.html
{% extends 'base.html' %}

{% block title %}Article::Update{% endblock title %}

{% block container %}
<form method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">Update</button>
</form>
{% endblock container %}