accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.password, name='password'), 
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/like/', views.like, name='like'),
    path('<int:article_pk>/comment_create/', views.comment_create, name='comment_create'),
    path('<int:comment_pk>/comment_delete/', views.comment_delete, name='comment_delete'),
    path('<int:article_pk>/follow/<int:user_pk>/', views.follow, name='follow'),
]

review/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
]

review/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  {% comment %} Bootstrap {% endcomment %}
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-reboot.min.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-grid.min.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
  {% comment %} FontAwesome {% endcomment %}
  <script src="https://kit.fontawesome.com/58a4b12f94.js" crossorigin="anonymous"></script>
  {% comment %} Axios {% endcomment %}
  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
  <title>{% block title %}{% endblock title %}</title>
</head>
<body>
  <header class="container">
    <h1>저희 페이지 오신걸 환영합니다.</h1>
    {% comment %} user 는 template 이 기본적으로 가지고 있는 정보 {% endcomment %}
    {% if user.is_authenticated %}
    <p>
      <span>Hello, {{ user.username }}</span>
      <a href="{% url 'accounts:logout' %}">[Logout]</a>
      <a href="{% url 'accounts:update' %}">[Update]</a>
      <form action="{% url 'accounts:delete' %}" method="POST">
        {% csrf_token %}
        <button class="btn-warning" type="submit">Delete</button>
      </form>
    </p>
    {% else %}
    <p>
      <a href="{% url 'accounts:login' %}">[Login]</a>
      <a href="{% url 'accounts:signup' %}">[Signup]</a>
    </p>
    {% endif %}
    <a href="{% url 'articles:index' %}">[List]</a>
    <hr>
  </header>
  <div class="container">
  {% block container %}{% endblock container %}
  </div>
  <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>